// <auto-generated />
using System;
using MetroQualityMonitor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetroQualityMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(MetroQualityMonitorDbContext))]
    [Migration("20260418204157_AddVestibulesAndPassengerFlow")]
    partial class AddVestibulesAndPassengerFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LineStation", b =>
                {
                    b.Property<short>("LinesId")
                        .HasColumnType("smallint");

                    b.Property<short>("StationsId")
                        .HasColumnType("smallint");

                    b.HasKey("LinesId", "StationsId");

                    b.HasIndex("StationsId");

                    b.ToTable("LineStation");
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.DataImports.Entities.DataImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Идентификатор записи");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Ключ файла в хранилище");

                    b.Property<DateTime>("CreateDateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время (UTC) создания записи");

                    b.Property<short>("DataType")
                        .HasColumnType("smallint")
                        .HasComment("Тип загруженного справочника");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Сообщение ошибки");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Наименование исходного файла");

                    b.Property<DateTime>("LoadedDateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время (UTC) загрузки файла");

                    b.Property<DateTime?>("ProcessingFinishedDateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время (UTC) завершения обработки");

                    b.Property<DateTime?>("ProcessingStartDateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время (UTC) начала обработки");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer")
                        .HasComment("Количество загруженных строк");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("SHA256 хэш");

                    b.Property<short>("SourceType")
                        .HasColumnType("smallint")
                        .HasComment("Метод загрузки данных");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasComment("Статус загрузки и обработки данных");

                    b.HasKey("Id");

                    b.HasIndex("DataType");

                    b.HasIndex("LoadedDateTimeUtc");

                    b.HasIndex("Sha256Hash");

                    b.HasIndex("Status");

                    b.ToTable("DataImportRuns", t =>
                        {
                            t.HasComment("Журнал загрузок исходных наборов данных");
                        });
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.PassengerFlow.Entities.PassengerFlowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("GlobalId")
                        .HasColumnType("bigint")
                        .HasComment("Глобальный идентификатор записи");

                    b.Property<int>("IncomingPassengers")
                        .HasColumnType("integer")
                        .HasComment("Количество входящих пассажиров");

                    b.Property<short?>("LineId")
                        .HasColumnType("smallint")
                        .HasComment("Идентификатор линии метро");

                    b.Property<int>("OutgoingPassengers")
                        .HasColumnType("integer")
                        .HasComment("Количество исходящих пассажиров");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Квартал");

                    b.Property<short?>("StationId")
                        .HasColumnType("smallint")
                        .HasComment("Идентификатор станции метро");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasComment("Год");

                    b.HasKey("Id");

                    b.HasIndex("GlobalId")
                        .IsUnique();

                    b.HasIndex("LineId");

                    b.HasIndex("StationId", "Year", "Quarter");

                    b.ToTable("PassengerFlowRecords", t =>
                        {
                            t.HasComment("Пассажиропоток по станции метро за квартал");
                        });
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.Stations.Entities.Line", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasComment("Идентификатор записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<long?>("GlobalId")
                        .HasColumnType("bigint")
                        .HasComment("Глобальный идентификатор записи");

                    b.Property<int?>("MosDataId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор в реестре открытых данных Москвы");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Наименование");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Статус линии");

                    b.HasKey("Id");

                    b.HasIndex("GlobalId")
                        .IsUnique();

                    b.HasIndex("MosDataId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Lines", t =>
                        {
                            t.HasComment("Линия метро");
                        });
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.Stations.Entities.Station", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasComment("Идентификатор записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Наименование");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Stations", t =>
                        {
                            t.HasComment("Станция метро");
                        });
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.Test.Entities.TestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время создания записи в UTC");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Наименование тестовой записи");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_TestEntities_Name")
                        .IsUnique();

                    b.ToTable("TestEntities", (string)null);
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.Vestibules.Entities.EscalatorRepair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("GlobalId")
                        .HasColumnType("bigint")
                        .HasComment("Глобальный идентификатор записи");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("Признак удалённой записи");

                    b.Property<string>("RepairPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Период ремонта (вида \"27.02.2023-30.05.2023\")");

                    b.Property<int>("VestibuleId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор вестибюля");

                    b.HasKey("Id");

                    b.HasIndex("GlobalId")
                        .IsUnique();

                    b.HasIndex("VestibuleId");

                    b.ToTable("EscalatorRepairs", t =>
                        {
                            t.HasComment("Сведения о ремонте эскалаторов вестибюля");
                        });
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.Vestibules.Entities.Vestibule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdmArea")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Административный округ");

                    b.Property<int?>("BPAAmount")
                        .HasColumnType("integer")
                        .HasComment("Общее количество БПА");

                    b.Property<string>("CulturalHeritageSiteStatus")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("Статус объекта культурного наследия");

                    b.Property<string>("District")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Район");

                    b.Property<int?>("FullFeaturedBPAAmount")
                        .HasColumnType("integer")
                        .HasComment("Количество полнофункциональных БПА");

                    b.Property<long>("GlobalId")
                        .HasColumnType("bigint")
                        .HasComment("Глобальный идентификатор записи");

                    b.Property<double?>("LatitudeWgs84")
                        .HasColumnType("double precision")
                        .HasComment("Широта (WGS84)");

                    b.Property<short?>("LineId")
                        .HasColumnType("smallint")
                        .HasComment("Идентификатор линии метро");

                    b.Property<int?>("LittleFunctionalBPAAmount")
                        .HasColumnType("integer")
                        .HasComment("Количество малофункциональных БПА");

                    b.Property<double?>("LongitudeWgs84")
                        .HasColumnType("double precision")
                        .HasComment("Долгота (WGS84)");

                    b.Property<string>("ModeOnEvenDays")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Режим работы по чётным дням");

                    b.Property<string>("ModeOnOddDays")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Режим работы по нечётным дням");

                    b.Property<int>("MosDataId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор в реестре открытых данных Москвы");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Наименование вестибюля");

                    b.Property<string>("ObjectStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Статус объекта");

                    b.Property<bool?>("OnTerritoryOfMoscow")
                        .HasColumnType("boolean")
                        .HasComment("Расположен на территории Москвы");

                    b.Property<int?>("ReleaseNumber")
                        .HasColumnType("integer")
                        .HasComment("Номер релиза набора данных");

                    b.Property<short?>("StationId")
                        .HasColumnType("smallint")
                        .HasComment("Идентификатор станции метро");

                    b.Property<int?>("VersionNumber")
                        .HasColumnType("integer")
                        .HasComment("Номер версии набора данных");

                    b.Property<string>("VestibuleType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Тип вестибюля");

                    b.HasKey("Id");

                    b.HasIndex("GlobalId")
                        .IsUnique();

                    b.HasIndex("LineId");

                    b.HasIndex("MosDataId")
                        .IsUnique();

                    b.HasIndex("StationId");

                    b.ToTable("Vestibules", t =>
                        {
                            t.HasComment("Вестибюль (вход/выход) станции метро");
                        });
                });

            modelBuilder.Entity("LineStation", b =>
                {
                    b.HasOne("MetroQualityMonitor.Domain.Stations.Entities.Line", null)
                        .WithMany()
                        .HasForeignKey("LinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroQualityMonitor.Domain.Stations.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("StationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.PassengerFlow.Entities.PassengerFlowRecord", b =>
                {
                    b.HasOne("MetroQualityMonitor.Domain.Stations.Entities.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId");

                    b.HasOne("MetroQualityMonitor.Domain.Stations.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId");

                    b.Navigation("Line");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.Vestibules.Entities.EscalatorRepair", b =>
                {
                    b.HasOne("MetroQualityMonitor.Domain.Vestibules.Entities.Vestibule", "Vestibule")
                        .WithMany("EscalatorRepairs")
                        .HasForeignKey("VestibuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vestibule");
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.Vestibules.Entities.Vestibule", b =>
                {
                    b.HasOne("MetroQualityMonitor.Domain.Stations.Entities.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId");

                    b.HasOne("MetroQualityMonitor.Domain.Stations.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId");

                    b.Navigation("Line");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.Vestibules.Entities.Vestibule", b =>
                {
                    b.Navigation("EscalatorRepairs");
                });
#pragma warning restore 612, 618
        }
    }
}
