// <auto-generated />
using System;
using MetroQualityMonitor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetroQualityMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(MetroQualityMonitorDbContext))]
    [Migration("20260314192808_AddLineStations")]
    partial class AddLineStations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LineStation", b =>
                {
                    b.Property<short>("LinesId")
                        .HasColumnType("smallint");

                    b.Property<short>("StationsId")
                        .HasColumnType("smallint");

                    b.HasKey("LinesId", "StationsId");

                    b.HasIndex("StationsId");

                    b.ToTable("LineStation");
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.DataImports.Entities.DataImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Идентификатор записи");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Ключ файла в хранилище");

                    b.Property<DateTime>("CreateDateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время (UTC) создания записи");

                    b.Property<short>("DataType")
                        .HasColumnType("smallint")
                        .HasComment("Тип загруженного справочника");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Сообщение ошибки");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Наименование исходного файла");

                    b.Property<DateTime>("LoadedDateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время (UTC) загрузки файла");

                    b.Property<DateTime?>("ProcessingFinishedDateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время (UTC) завершения обработки");

                    b.Property<DateTime?>("ProcessingStartDateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время (UTC) начала обработки");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer")
                        .HasComment("Количество загруженных строк");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("SHA256 хэш");

                    b.Property<short>("SourceType")
                        .HasColumnType("smallint")
                        .HasComment("Метод загрузки данных");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasComment("Статус загрузки и обработки данных");

                    b.HasKey("Id");

                    b.HasIndex("DataType");

                    b.HasIndex("LoadedDateTimeUtc");

                    b.HasIndex("Sha256Hash");

                    b.HasIndex("Status");

                    b.ToTable("DataImportRuns", t =>
                        {
                            t.HasComment("Журнал загрузок исходных наборов данных");
                        });
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.Stations.Entities.Line", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasComment("Идентификатор записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Наименование");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Lines", t =>
                        {
                            t.HasComment("Линия метро");
                        });
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.Stations.Entities.Station", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasComment("Идентификатор записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Наименование");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Stations", t =>
                        {
                            t.HasComment("Станция метро");
                        });
                });

            modelBuilder.Entity("MetroQualityMonitor.Domain.Test.Entities.TestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDateTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата и время создания записи в UTC");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Наименование тестовой записи");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_TestEntities_Name")
                        .IsUnique();

                    b.ToTable("TestEntities", (string)null);
                });

            modelBuilder.Entity("LineStation", b =>
                {
                    b.HasOne("MetroQualityMonitor.Domain.Stations.Entities.Line", null)
                        .WithMany()
                        .HasForeignKey("LinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroQualityMonitor.Domain.Stations.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("StationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
